bookyourdoctor/Controllers/Hospital_requestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class Hospital_requestController : Controller
    {
        public static string ideee = patientsController.idee;
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: Hospital_request
        public ActionResult Index()
        {
            return View(db.Hospital_request.ToList());
        }

        // GET: Hospital_request/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            if (hospital_request == null)
            {
                return HttpNotFound();
            }
            return View(hospital_request);
        }

        public ActionResult Create1(int idee)
        {
            try
            {
                Hospital_request p = new Hospital_request();
                doctor_scedule doctor_shedule = db.doctor_scedule.Find(idee);
                p.doctor_id = doctor_shedule.doctor_id;
                p.Hospital_day = doctor_shedule.hospial_day;
                p.patient_name = ideee;
                p.Hospital_start_time = doctor_shedule.hospital_start_time;
                p.hospital_end_time = doctor_shedule.hospital_end_time;

                db.Hospital_request.Add(p);

                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            return RedirectToAction("Index1","Clinic_request");
        }
        

        // GET: Hospital_request/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hospital_request/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Hospital_start_time,hospital_end_time,patient_name,Hospital_day,id,doctor_id")] Hospital_request hospital_request)
        {
            if (ModelState.IsValid)
            {
                db.Hospital_request.Add(hospital_request);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hospital_request);
        }

        // GET: Hospital_request/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            if (hospital_request == null)
            {
                return HttpNotFound();
            }
            return View(hospital_request);
        }

        // POST: Hospital_request/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Hospital_start_time,hospital_end_time,patient_name,Hospital_day,id,doctor_id")] Hospital_request hospital_request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hospital_request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospital_request);
        }

        // GET: Hospital_request/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            if (hospital_request == null)
            {
                return HttpNotFound();
            }
            return View(hospital_request);
        }

        // POST: Hospital_request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            db.Hospital_request.Remove(hospital_request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Controllers/hospital_viewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class hospital_viewController : Controller
    {
        public static string ideee = patientsController.idee;
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: hospital_view
        public ActionResult Index()
        {
            return View(db.hospital_view.ToList());
        }

        public ActionResult Create1(int idee, bookyourdoctor.Models.gmailsent model)
        {
            try
            {
                hospital_view p = new hospital_view();
                Hospital_request hospital_Request = db.Hospital_request.Find(idee);

                p.Hospital_day = hospital_Request.Hospital_day;
                p.patient_name = hospital_Request.patient_name;
                p.hospital_start_time = hospital_Request.Hospital_start_time;
                p.hospital_end_time = hospital_Request.hospital_end_time;

                db.hospital_view.Add(p);
                db.SaveChanges();

                MailMessage mm = new MailMessage("maham.asif456@gmail.com", ideee);//model.To ki jagah patient i

                mm.Subject = "APPOINTMENT STATUS";
                model.Subject = mm.Subject;
                mm.Body = p.patient_name + "" + "Your request has been rejected" + ". " + "You need to come to the hospital at time" + "" + model.startTime + " " + "to" + model.endTime + "" + "on" + "" + p.Hospital_day;
                model.Body = mm.Body;

                mm.IsBodyHtml = false;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.EnableSsl = true;
                smtp.Port = 587;
                NetworkCredential nc = new NetworkCredential("maham.asif456@gmail.com", "maham180598");
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = nc;
                smtp.Send(mm);
                ViewBag.Message = "Mail has been sent successfully";
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            return RedirectToAction("Index2", "Clinic_request");
        }
        public ActionResult Create2(int idee, bookyourdoctor.Models.gmailsent model)
        {

            hospital_view p = new hospital_view();
            Hospital_request hospital_Request = db.Hospital_request.Find(idee);

            p.Hospital_day = hospital_Request.Hospital_day;
            p.patient_name = hospital_Request.patient_name;
            p.hospital_start_time = hospital_Request.Hospital_start_time;
            p.hospital_end_time = hospital_Request.hospital_end_time;

            db.hospital_view.Add(p);
            db.SaveChanges();
            MailMessage mm = new MailMessage("maham.asif456@gmail.com", ideee);//model.To ki jagah patient i

            mm.Subject = "APPOINTMENT STATUS";
            model.Subject = mm.Subject;
            mm.Body = p.patient_name + "" + "Your request has been rejected" + ". " + "You need to come to the hospital at time" + "" + model.startTime + " " + "to" + model.endTime + "" + "on" + "" + p.Hospital_day;
            model.Body = mm.Body;

            mm.IsBodyHtml = false;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.EnableSsl = true;
            smtp.Port = 587;
            NetworkCredential nc = new NetworkCredential("maham.asif456@gmail.com", "maham180598");
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = nc;
            smtp.Send(mm);
            ViewBag.Message = "Mail has been sent successfully";

            return RedirectToAction("Index2", "Clinic_request");
            //return RedirectToAction("Index1");
        }

        public ActionResult Index1()
        {
            return View();
        }

        // GET: hospital_view/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            hospital_view hospital_view = db.hospital_view.Find(id);
            if (hospital_view == null)
            {
                return HttpNotFound();
            }
            return View(hospital_view);
        }

        // GET: hospital_view/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: hospital_view/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "hospital_end_time,hospital_start_time,patient_name,Hospital_day,id")] hospital_view hospital_view)
        {
            if (ModelState.IsValid)
            {
                db.hospital_view.Add(hospital_view);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hospital_view);
        }

        // GET: hospital_view/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            hospital_view hospital_view = db.hospital_view.Find(id);
            if (hospital_view == null)
            {
                return HttpNotFound();
            }
            return View(hospital_view);
        }

        // POST: hospital_view/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "hospital_end_time,hospital_start_time,patient_name,Hospital_day,id")] hospital_view hospital_view)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hospital_view).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospital_view);
        }

        // GET: hospital_view/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            hospital_view hospital_view = db.hospital_view.Find(id);
            if (hospital_view == null)
            {
                return HttpNotFound();
            }
            return View(hospital_view);
        }

        // POST: hospital_view/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            hospital_view hospital_view = db.hospital_view.Find(id);
            db.hospital_view.Remove(hospital_view);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Views/Hospital_request/Create.cshtml
@model bookyourdoctor.Hospital_request
@{
    ViewBag.Title = "Create";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">CREATE REQUEST</b></center>
                @using (Html.BeginForm())
    {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
               
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Hospital_start_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Hospital_start_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Hospital_start_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.hospital_end_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.hospital_end_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.hospital_end_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.patient_name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.patient_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.patient_name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Hospital_day, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Hospital_day, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Hospital_day, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.doctor_id, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.doctor_id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
}
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/Hospital_request/Delete.cshtml
@model bookyourdoctor.Hospital_request
@{
    ViewBag.Title = "Delete";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">DELETE REQUEST</b></center>
                <h3>Are you sure you want to delete this?</h3>
                <div>
                    
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Hospital_start_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Hospital_start_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.hospital_end_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.hospital_end_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.patient_name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.patient_name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Hospital_day)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Hospital_day)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.doctor_id)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.doctor_id)
                        </dd>
                    </dl>
                    @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
}
                </div>

            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/Hospital_request/Details.cshtml
@model bookyourdoctor.Hospital_request
@{
    ViewBag.Title = "Details";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">REQUEST DETAILS</b></center>
                <div>
                    
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Hospital_start_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Hospital_start_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.hospital_end_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.hospital_end_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.patient_name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.patient_name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Hospital_day)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Hospital_day)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.doctor_id)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.doctor_id)
                        </dd>
                    </dl>
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>

            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/Hospital_request/Edit.cshtml
@model bookyourdoctor.Hospital_request
@{
    ViewBag.Title = "Edit";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">EDIT REQUEST</b></center>
                @using (Html.BeginForm())
    {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Hospital_start_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Hospital_start_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Hospital_start_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.hospital_end_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.hospital_end_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.hospital_end_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.patient_name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.patient_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.patient_name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Hospital_day, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Hospital_day, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Hospital_day, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.id)
                <div class="form-group">
                    @Html.LabelFor(model => model.doctor_id, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.doctor_id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
}
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/Hospital_request/Index.cshtml
@model IEnumerable<bookyourdoctor.Hospital_request>
@{
    ViewBag.Title = "Index";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">HOSPITAL REQUESTS</b></center>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.patient_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Hospital_day)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Hospital_start_time)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.hospital_end_time)
                        </th>
                        <th>
                            <h2> REQUEST STATUS</h2>
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.patient_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hospital_day)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hospital_start_time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.hospital_end_time)
                </td>
                <td>
                    @Html.ActionLink("ACCEPT", "Create1", "hospital_view", new { idee = item.id }, null)
                    @Html.ActionLink("REJECT", "Create2", "hospital_view", new { idee = item.id }, null)
                </td>
            </tr>
}
                </table>
            </div>
        </div>
    </div>
</body>